// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PreClear.Api.Data;

#nullable disable

namespace backend.Migrations.Auto
{
    [DbContext(typeof(PreclearDbContext))]
    [Migration("20251215042304_AddShipmentDocumentFields")]
    partial class AddShipmentDocumentFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PreClear.Api.Models.AiFinding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<string>("Details")
                        .HasColumnType("json")
                        .HasColumnName("details");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("RuleCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("rule_code");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("warning")
                        .HasColumnName("severity");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<string>("SuggestedAction")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("suggested_action");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_aifindings_shipment");

                    b.ToTable("ai_findings", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ApprovalLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action");

                    b.Property<long?>("ApproverId")
                        .HasColumnType("bigint")
                        .HasColumnName("approver_id");

                    b.Property<string>("ApproverRole")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("approver_role");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("entity");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("json")
                        .HasColumnName("metadata");

                    b.Property<string>("NewState")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("new_state");

                    b.Property<string>("PreviousState")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("previous_state");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId")
                        .HasDatabaseName("idx_approval_approver");

                    b.HasIndex("Entity", "EntityId")
                        .HasDatabaseName("idx_approval_entity");

                    b.ToTable("approval_logs", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action");

                    b.Property<string>("Details")
                        .HasColumnType("json")
                        .HasColumnName("details");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("entity");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<DateTime>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("performed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Entity", "EntityId")
                        .HasDatabaseName("idx_audit_entity");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.BrokerRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("fulfilled_at");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("RequestedDocument")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("requested_document");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Open")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_brokerrequests_shipment");

                    b.ToTable("broker_requests", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.BrokerReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("BrokerId")
                        .HasColumnType("bigint")
                        .HasColumnName("broker_id");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("reviewed_at");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_brokerreviews_shipment");

                    b.ToTable("broker_reviews", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ImportExportRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("effective_to");

                    b.Property<string>("HsCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("hs_code");

                    b.Property<string>("RuleJson")
                        .HasColumnType("json")
                        .HasColumnName("rule_json");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("rule_key");

                    b.Property<string>("Source")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Active")
                        .HasDatabaseName("idx_rules_active");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("idx_rules_country");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("HsCode")
                        .HasDatabaseName("idx_rules_hs");

                    b.HasIndex("RuleKey")
                        .HasDatabaseName("idx_rules_key");

                    b.ToTable("import_export_rules", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_notifications_user");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("paid_at");

                    b.Property<string>("Payer")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Shipper")
                        .HasColumnName("payer");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("payment_status");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.HasKey("Id");

                    b.HasIndex("PaymentStatus")
                        .HasDatabaseName("idx_payments_status");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_payments_shipment");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.RuleChangeRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<string>("ProposedRuleJson")
                        .HasColumnType("json")
                        .HasColumnName("proposed_rule_json");

                    b.Property<long?>("ProposerId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposer_id");

                    b.Property<string>("Rationale")
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("reviewed_at");

                    b.Property<long?>("ReviewedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("reviewed_by");

                    b.Property<long?>("RuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("rule_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProposerId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("RuleId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_rcr_status");

                    b.ToTable("rule_change_requests", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.Shipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("UPS")
                        .HasColumnName("carrier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Ground")
                        .HasColumnName("mode");

                    b.Property<string>("PreclearToken")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("preclear_token");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("reference_id");

                    b.Property<string>("ShipmentName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("shipment_name");

                    b.Property<string>("ShipmentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("International")
                        .HasColumnName("shipment_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Mode")
                        .HasDatabaseName("idx_shipments_mode");

                    b.HasIndex("ReferenceId")
                        .HasDatabaseName("idx_shipments_reference");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_shipments_status");

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentCompliance", b =>
                {
                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<string>("AiNotes")
                        .HasColumnType("json")
                        .HasColumnName("ai_notes");

                    b.Property<int?>("AiScore")
                        .HasColumnType("int")
                        .HasColumnName("ai_score");

                    b.Property<string>("AiStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("NeedsDocuments")
                        .HasColumnName("ai_status");

                    b.Property<bool>("DangerousGoods")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("dangerous_goods");

                    b.Property<string>("Eccn")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("eccn");

                    b.Property<bool>("ExportLicenseRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("export_license_required");

                    b.Property<bool>("FoodPharmaFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("food_pharma_flag");

                    b.Property<bool>("LithiumBattery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("lithium_battery");

                    b.Property<bool>("RestrictedFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("restricted_flag");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Low")
                        .HasColumnName("risk_level");

                    b.Property<bool>("SanctionedCountryFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("sanctioned_country_flag");

                    b.HasKey("ShipmentId");

                    b.HasIndex("AiStatus")
                        .HasDatabaseName("idx_compliance_ai_status");

                    b.ToTable("shipment_compliance", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Other")
                        .HasColumnName("document_type");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("file_url");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<bool>("Required")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("required");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<bool>("Uploaded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("uploaded");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<long?>("UploadedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by");

                    b.Property<bool>("VerifiedByBroker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("verified_by_broker");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_documents_shipment");

                    b.ToTable("shipment_documents", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country_of_origin");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExportReason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Sale")
                        .HasColumnName("export_reason");

                    b.Property<string>("HsCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("hs_code");

                    b.Property<string>("ProductName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("product_name");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValue(1m)
                        .HasColumnName("quantity");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<decimal?>("TotalValue")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("total_value");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("pcs")
                        .HasColumnName("unit");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("HsCode")
                        .HasDatabaseName("idx_items_hscode");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_items_shipment");

                    b.ToTable("shipment_items", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<long?>("SenderId")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_id");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_msgs_shipment");

                    b.ToTable("shipment_messages", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentPackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("DimensionUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("cm")
                        .HasColumnName("dimension_unit");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("height");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("length");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Box")
                        .HasColumnName("package_type");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<bool>("Stackable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("stackable");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("weight");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("kg")
                        .HasColumnName("weight_unit");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_packages_shipment");

                    b.ToTable("shipment_packages", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentParty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Address1")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address2");

                    b.Property<string>("City")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("contact_name");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("party_type");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("postal_code");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<string>("State")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("state");

                    b.Property<string>("TaxId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_parties_shipment");

                    b.ToTable("shipment_parties", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentService", b =>
                {
                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<string>("BillTo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Shipper")
                        .HasColumnName("bill_to");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<decimal?>("DeclaredValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("declared_value");

                    b.Property<string>("Incoterm")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("incoterm");

                    b.Property<bool>("InsuranceRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("insurance_required");

                    b.Property<string>("ServiceLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Standard")
                        .HasColumnName("service_level");

                    b.HasKey("ShipmentId");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_services_shipment");

                    b.ToTable("shipment_services", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentTracking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<string>("Details")
                        .HasColumnType("json")
                        .HasColumnName("details");

                    b.Property<DateTime?>("EventTime")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("event_time");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Status")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_tracking_shipment");

                    b.ToTable("shipment_tracking", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("first_name");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("invite_code");

                    b.Property<DateTime?>("InviteExpiresAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("invite_expires_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("last_name");

                    b.Property<string>("Metadata")
                        .HasColumnType("json")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("longtext")
                        .HasColumnName("name")
                        .HasComputedColumnSql("CONCAT(COALESCE(first_name,''),' ',COALESCE(last_name,''))", false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.Property<bool>("TosAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("tos_accepted");

                    b.Property<DateTime?>("TosAcceptedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("tos_accepted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("verification_token");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_users_active");

                    b.HasIndex("Role")
                        .HasDatabaseName("idx_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.AiFinding", b =>
                {
                    b.HasOne("PreClear.Api.Models.Shipment", null)
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aifindings_shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.ApprovalLog", b =>
                {
                    b.HasOne("PreClear.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PreClear.Api.Models.AuditLog", b =>
                {
                    b.HasOne("PreClear.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_user");
                });

            modelBuilder.Entity("PreClear.Api.Models.BrokerRequest", b =>
                {
                    b.HasOne("PreClear.Api.Models.Shipment", null)
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brokerrequests_shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.BrokerReview", b =>
                {
                    b.HasOne("PreClear.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_brokerreviews_broker");

                    b.HasOne("PreClear.Api.Models.Shipment", null)
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brokerreviews_shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.ImportExportRule", b =>
                {
                    b.HasOne("PreClear.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PreClear.Api.Models.Notification", b =>
                {
                    b.HasOne("PreClear.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_user");
                });

            modelBuilder.Entity("PreClear.Api.Models.Payment", b =>
                {
                    b.HasOne("PreClear.Api.Models.Shipment", null)
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.RuleChangeRequest", b =>
                {
                    b.HasOne("PreClear.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ProposerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PreClear.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PreClear.Api.Models.ImportExportRule", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PreClear.Api.Models.Shipment", b =>
                {
                    b.HasOne("PreClear.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_shipments_createdby");
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentCompliance", b =>
                {
                    b.HasOne("PreClear.Api.Models.Shipment", null)
                        .WithOne()
                        .HasForeignKey("PreClear.Api.Models.ShipmentCompliance", "ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_compliance_shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentDocument", b =>
                {
                    b.HasOne("PreClear.Api.Models.Shipment", null)
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_docs_shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentItem", b =>
                {
                    b.HasOne("PreClear.Api.Models.Shipment", null)
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentMessage", b =>
                {
                    b.HasOne("PreClear.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_msgs_sender");

                    b.HasOne("PreClear.Api.Models.Shipment", null)
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_msgs_shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentPackage", b =>
                {
                    b.HasOne("PreClear.Api.Models.Shipment", null)
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_packages_shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentParty", b =>
                {
                    b.HasOne("PreClear.Api.Models.Shipment", null)
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parties_shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentService", b =>
                {
                    b.HasOne("PreClear.Api.Models.Shipment", null)
                        .WithOne()
                        .HasForeignKey("PreClear.Api.Models.ShipmentService", "ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_services_shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentTracking", b =>
                {
                    b.HasOne("PreClear.Api.Models.Shipment", null)
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tracking_shipment");
                });
#pragma warning restore 612, 618
        }
    }
}
